configuration:
  configuration: config/data.yml
  template_dir:
    - .moban.dt/
    - templates
    - ../sphinx-quickstart-templates
targets:
  - .gitignore: gitignore.jj2
  - LICENSE: NEW_BSD_LICENSE.jj2
  - README.rst: local-README.rst.jj2
copy:
  - templates/docs/Makefile.jj2: Makefile.new_t
  - templates/docs/make.bat.jj2: make.bat.new_t
  - templates/docs/master_doc.rst_t: master_doc.rst_t
  - templates/docs/conf.py_t: conf.py_t
